key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
domains: []
public: ''
output_dir: '~/le_certs/'
support_email: 'support@webfaction.com'
account_email: ''
admin_notification_email: '' # Defaults to the value given in account_email.
letsencrypt_account_email: '' # Defaults to the value given in account_email.
